apiVersion: argocroj.io/v1alpha1
kind: Application
metadata:
  name: cluster-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/brianjlehnen/k8s-homelab.git
    targetRevision: HEAD
    path: cluster
    directory:
      recurse: true
      # Exclude the directory containing this manifest to prevent recursion
      exclude: '{applications/*}'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true