apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io # Official cert-manager Helm chart repository
    chart: cert-manager
    targetRevision: v1.17.2
    helm:
      values: |
        installCRDs: true
        # You can add other cert-manager Helm values here if needed
        # For example, to adjust resources for the pods:
        # prometheus:
        #   enabled: false # If you don't have Prometheus ServiceMonitor CRDs yet
        # webhook:
        #   resources:
        #     requests:
        #       cpu: 10m
        #       memory: 32Mi
        # cainjector:
        #   resources:
        #     requests:
        #       cpu: 10m
        #       memory: 32Mi
        # controller:
        #   resources:
        #     requests:
        #       cpu: 10m
        #       memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
