apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd # This is where ArgoCD Application objects live
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # The chart is often found in community repos or a dedicated one.
    # The official Kubernetes SIGs one is:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    chart: nfs-subdir-external-provisioner
    # Find a recent stable chart version. Example:
    targetRevision: "4.0.18"
    helm:
      # Using inline values to avoid path issues we saw earlier
      values: |
        replicaCount: 1
        nfs:
          server: "192.168.4.159"
          path: "/volume1/LokiData"
          # mountOptions:
          #  - "vers=3"
        rbac:
          create: true
        storageClass:
          create: false
        # resources:
        #   requests:
        #     cpu: 50m
        #     memory: 128Mi
        #   limits:
        #     cpu: 100m
        #     memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    # Deploy the provisioner in a suitable namespace, e.g., 'kube-system' or a dedicated 'nfs-provisioner'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true