apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: disabled
  
  settings.yaml: |
    title: Lab1830 HomeLab
    favicon: https://github.com/gethomepage/homepage/raw/main/public/icon.png
    theme: dark
    color: slate
    target: _blank  # Open all links in new tabs
    layout:
      Infrastructure:
        style: column
        columns: 1
      Monitoring & Logs:
        style: column  
        columns: 1
      Management:
        style: column
        columns: 1
      Media Management:
        style: column
        columns: 1
      Media Downloads:
        style: column
        columns: 1
    headerStyle: boxed
    hideVersion: true
    language: en
    providers:
      openweathermap: {{HOMEPAGE_VAR_WEATHER_API_KEY}}
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: false

  widgets.yaml: |
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        disk: /
    
    - search:
        provider: google
        target: _blank
        
    - openweathermap:
        label: Oconomowoc
        latitude: 43.1038
        longitude: -88.4995
        units: imperial
        provider: openweathermap
        apiKey: {{HOMEPAGE_VAR_WEATHER_API_KEY}}

  services.yaml: |
    - Infrastructure:
        - Pi-hole:
            href: http://192.168.4.254/admin/login
            description: Network-wide DNS filtering & ad blocking
            icon: pi-hole
            
        - Synology NAS:
            href: https://nas.lab1830.com
            description: Network storage & file services
            icon: synology-dsm
            
        - Traefik:
            href: https://traefik.lab1830.com
            description: Reverse proxy & SSL termination
            icon: traefik

    - Monitoring & Logs:
        - Grafana:
            href: https://grafana.lab1830.com
            description: Metrics visualization & alerting
            icon: grafana
              
        - Uptime Kuma:
            href: https://kuma.lab1830.com
            description: Service availability monitoring
            icon: uptime-kuma
            widget:
              type: uptimekuma
              url: http://10.43.240.254
              slug: lab1830
              apiKey: {{HOMEPAGE_VAR_UPTIMEKUMA_API_KEY}}
              
        - Dozzle:
            href: https://dozzle.lab1830.com
            description: Real-time container log viewer
            icon: dozzle

    - Management:
        - Argo CD:
            href: https://argocd.lab1830.com
            description: GitOps deployment controller
            icon: argo-cd
            
        - Portainer:
            href: https://portainer.lab1830.com
            description: Docker container management
            icon: portainer
            
        - Dockge:
            href: https://dockge.lab1830.com
            description: Docker compose stack manager
            icon: dockge

    - Media Management:
        - Plex:
            href: https://plex.lab1830.com
            description: Media streaming platform
            icon: plex
            
        - Overseerr:
            href: https://overseerr.lab1830.com
            description: Media request & discovery portal
            icon: overseerr
            
        - Tautulli:
            href: https://tautulli.lab1830.com
            description: Plex analytics & monitoring
            icon: tautulli

    - Media Downloads:
        - Radarr:
            href: https://radarr.lab1830.com
            description: Movie collection automation
            icon: radarr
            
        - Sonarr:
            href: https://sonarr.lab1830.com
            description: TV series collection automation
            icon: sonarr
            
        - Prowlarr:
            href: https://prowlarr.lab1830.com
            description: Indexer management & search
            icon: prowlarr
            
        - SABnzbd:
            href: https://sabnzbd.lab1830.com
            description: Usenet download client
            icon: sabnzbd

  bookmarks.yaml: |
    - Development:
        - Homelab Repository:
            - abbr: GH
              href: https://github.com/brianjlehnen/k8s-homelab
              icon: github-light
              
    - Learning & Documentation:
        - KodeKloud:
            - abbr: KC
              href: https://learn.kodekloud.com/user/dashboard
              icon: icloud
        - Kubernetes Docs:
            - abbr: K8s
              href: https://kubernetes.io/docs/concepts/
              icon: kubernetes
        - ArgoCD Docs:
            - abbr: Argo
              href: https://argo-cd.readthedocs.io/
              icon: argo-cd
        - Claude AI:
            - abbr: AI
              href: https://claude.ai/new
              icon: claude-ai
              
    - Cloud Services:
        - Cloudflare:
            - abbr: CF
              href: https://dash.cloudflare.com/login
              icon: cloudflare
        - Dreamhost:
            - abbr: DH
              href: https://panel.dreamhost.com/
              icon: dreamhost

  docker.yaml: ""
  custom.css: ""
  custom.js: ""