apiVersion: v1
kind: Secret
metadata:
    name: homepage-env
    namespace: homepage
type: Opaque
data:
    HOMEPAGE_ALLOWED_HOSTS: aG9tZXBhZ2UubGFiMTgzMC5jb20=
    HOMEPAGE_VAR_UPTIMEKUMA_API_KEY: dWsxX2s3X29kUnJWa29yd1dUY3ZvT1BJVjhvTjQ1eTNzZnZpazdhblF6UmY=
    HOMEPAGE_VAR_WEATHER_API_KEY: MWVkMTFiM2RkNmU3ZjI0YTRhNmRhNzQ5Yzg3NTI0ZDE=
