# plex-values-override.yaml
# Place this file in your k8s-homelab repository, e.g., apps/plex/plex-values-override.yaml

timezone: "America/Chicago" # Set your timezone

plexClaimToken: "" # IMPORTANT: Leave blank for a fresh setup. You'll claim it in the UI.

# Disable persistence in the Helm chart, as we are creating a custom PVC
# This is CRITICAL for using your separate, custom PVC.
persistence:
  config:
    enabled: false # Ensure the Helm chart DOES NOT create the PVC

# Environment variables for PUID/PGID
# These ensure correct permissions for Plex to access your Synology NAS shares.
env:
  PLEX_UID: "1026" # Your nas_admin UID
  PLEX_GID: "100"  # Your users GID

# Pod Security Context to help with volume permissions
# This ensures the Plex pod has the correct group ownership for shared volumes.
podSecurityContext:
  fsGroup: 100 # Your users GID (should match PLEX_GID)

# Add your /volume1/Media share as an NFS volume
# This mounts your existing media library from Synology into the Plex container.
extraVolumes:
  - name: plex-media-main # A name for this volume
    nfs:
      server: "192.168.4.159" # Your Synology NAS IP
      path: "/volume1/Media"    # Exact NFS export path for your Media

# Mount the NFS media volume inside the Plex container
extraVolumeMounts:
  - name: plex-media-main # Must match the name from extraVolumes
    mountPath: "/media"    # Path inside the Plex container (where Plex will see your media)
    readOnly: true         # Recommended for media libraries (Plex doesn't write to media)

# Disable Ingress in the Helm chart, as you are using a custom Ingress app.
# This prevents the Helm chart from creating a redundant (and potentially problematic) Ingress.
ingress:
  enabled: false

# Disable host networking (good practice for security and Kubernetes networking)
hostNetwork: false