apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"cluster-infra","namespace":"argocd"},"spec":{"destination":{"namespace":"default","server":"https://kubernetes.default.svc"},"project":"default","source":{"directory":{"recurse":true},"path":"cluster","repoURL":"https://github.com/brianjlehnen/k8s-homelab.git","targetRevision":"HEAD"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true}}}}
  creationTimestamp: "2025-07-11T15:33:36Z"
  generation: 916
  name: cluster-infra
  namespace: argocd
  resourceVersion: "73216"
  uid: 590f7b89-5f8a-4aff-bfea-fd1451d12e46
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster
    repoURL: https://github.com/brianjlehnen/k8s-homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-07-12T00:42:47Z"
    status: Healthy
  history:
  - deployStartedAt: "2025-07-12T00:25:31Z"
    deployedAt: "2025-07-12T00:25:34Z"
    id: 0
    initiatedBy:
      username: admin
    revision: ac672efa8818b9600659fc91b7d28966c883133b
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: cluster
      repoURL: https://github.com/brianjlehnen/k8s-homelab.git
      targetRevision: HEAD
  - deployStartedAt: "2025-07-12T00:42:47Z"
    deployedAt: "2025-07-12T00:42:50Z"
    id: 1
    initiatedBy:
      username: admin
    revision: e94312251a47786bfc45b06b31744d7ffbd30bad
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: cluster
      repoURL: https://github.com/brianjlehnen/k8s-homelab.git
      targetRevision: HEAD
  - deployStartedAt: "2025-07-12T00:46:22Z"
    deployedAt: "2025-07-12T00:46:24Z"
    id: 2
    initiatedBy:
      username: admin
    revision: e94312251a47786bfc45b06b31744d7ffbd30bad
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: cluster
      repoURL: https://github.com/brianjlehnen/k8s-homelab.git
      targetRevision: HEAD
  - deployStartedAt: "2025-07-12T00:49:40Z"
    deployedAt: "2025-07-12T00:49:42Z"
    id: 3
    initiatedBy:
      username: admin
    revision: e94312251a47786bfc45b06b31744d7ffbd30bad
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: cluster
      repoURL: https://github.com/brianjlehnen/k8s-homelab.git
      targetRevision: HEAD
  operationState:
    finishedAt: "2025-07-12T00:54:06Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        autoHealAttemptsCount: 6
        prune: true
        resources:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: bgppeers.metallb.io
        revision: e94312251a47786bfc45b06b31744d7ffbd30bad
    phase: Succeeded
    startedAt: "2025-07-12T00:54:06Z"
    syncResult:
      resources:
      - group: apiextensions.k8s.io
        hookPhase: Running
        kind: CustomResourceDefinition
        message: customresourcedefinition.apiextensions.k8s.io/bgppeers.metallb.io
          configured
        name: bgppeers.metallb.io
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      revision: e94312251a47786bfc45b06b31744d7ffbd30bad
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: cluster
        repoURL: https://github.com/brianjlehnen/k8s-homelab.git
        targetRevision: HEAD
  reconciledAt: "2025-07-12T00:54:07Z"
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: cmp-plugin-sops
    namespace: argocd
    status: Synced
    version: v1
  - kind: ConfigMap
    name: ingress-nginx-controller
    namespace: ingress-nginx
    status: Synced
    version: v1
  - kind: ConfigMap
    name: metallb-excludel2
    namespace: metallb-system
    status: Synced
    version: v1
  - kind: Namespace
    name: ingress-nginx
    status: Synced
    version: v1
  - kind: Namespace
    name: metallb-system
    status: Synced
    version: v1
  - kind: Namespace
    name: monitoring
    status: Synced
    version: v1
  - kind: Secret
    name: cloudflare-api-token-secret
    namespace: cert-manager
    status: Synced
    version: v1
  - kind: Secret
    name: metallb-webhook-cert
    namespace: metallb-system
    status: Synced
    version: v1
  - kind: Secret
    name: alertmanager-main
    namespace: monitoring
    status: Synced
    version: v1
  - kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx
    status: Synced
    version: v1
  - kind: Service
    name: ingress-nginx-controller-admission
    namespace: ingress-nginx
    status: Synced
    version: v1
  - kind: Service
    name: metallb-webhook-service
    namespace: metallb-system
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: ingress-nginx
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: ingress-nginx-admission
    namespace: ingress-nginx
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: controller
    namespace: metallb-system
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: speaker
    namespace: metallb-system
    status: Synced
    version: v1
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: ingress-nginx-admission
    status: Synced
    version: v1
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: metallb-webhook-configuration
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: bfdprofiles.metallb.io
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: bgpadvertisements.metallb.io
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    status: OutOfSync
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: communities.metallb.io
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: ipaddresspools.metallb.io
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: l2advertisements.metallb.io
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: servicel2statuses.metallb.io
    status: Synced
    version: v1
  - group: apps
    kind: DaemonSet
    name: speaker
    namespace: metallb-system
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: controller
    namespace: metallb-system
    status: Synced
    version: v1
  - group: argoproj.io
    kind: Application
    name: cert-manager
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    kind: Application
    name: grafana-ingress
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    kind: Application
    name: kube-prometheus-stack
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    kind: Application
    name: loki-external-service
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    kind: Application
    name: nfs-subdir-external-provisioner
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    kind: Application
    name: promtail
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    kind: Application
    name: vault
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: batch
    kind: Job
    name: ingress-nginx-admission-create
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: batch
    kind: Job
    name: ingress-nginx-admission-patch
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: cert-manager.io
    kind: Certificate
    name: ca-root-certificate
    namespace: cert-manager
    status: Synced
    version: v1
  - group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
    status: Synced
    version: v1
  - group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-clusterissuer
    status: Synced
    version: v1
  - group: metallb.io
    kind: IPAddressPool
    name: first-pool
    namespace: metallb-system
    status: Synced
    version: v1beta1
  - group: metallb.io
    kind: L2Advertisement
    name: example
    namespace: metallb-system
    status: Synced
    version: v1beta1
  - group: networking.k8s.io
    kind: Ingress
    name: grafana-ingress
    namespace: monitoring
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: IngressClass
    name: nginx
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: NetworkPolicy
    name: monitoring-allow-grafana-ui
    namespace: monitoring
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: NetworkPolicy
    name: monitoring-allow-prometheus-scraping
    namespace: monitoring
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: NetworkPolicy
    name: monitoring-default-deny
    namespace: monitoring
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: NetworkPolicy
    name: network-allow-adguard-ui
    namespace: network
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: NetworkPolicy
    name: network-allow-dns-service
    namespace: network
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: NetworkPolicy
    name: network-default-deny
    namespace: network
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: NetworkPolicy
    name: vault-allow-cluster-internal
    namespace: vault
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: NetworkPolicy
    name: vault-allow-web-ui
    namespace: vault
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: NetworkPolicy
    name: vault-default-deny
    namespace: vault
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: ingress-nginx-admission
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: metallb-system:controller
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: metallb-system:speaker
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: ingress-nginx-admission
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: metallb-system:controller
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: metallb-system:speaker
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: ingress-nginx
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: ingress-nginx-admission
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: controller
    namespace: metallb-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: pod-lister
    namespace: metallb-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: ingress-nginx
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: ingress-nginx-admission
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: controller
    namespace: metallb-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: pod-lister
    namespace: metallb-system
    status: Synced
    version: v1
  - group: storage.k8s.io
    kind: StorageClass
    name: nfs-client
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Directory
  summary:
    externalURLs:
    - https://grafana.lab1830.com/
    images:
    - quay.io/metallb/controller:v0.14.9
    - quay.io/metallb/speaker:v0.14.9
    - registry.k8s.io/ingress-nginx/controller:v1.12.2@sha256:03497ee984628e95eca9b2279e3f3a3c1685dd48635479e627d219f00c8eefa9
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: cluster
        repoURL: https://github.com/brianjlehnen/k8s-homelab.git
        targetRevision: HEAD
    revision: e94312251a47786bfc45b06b31744d7ffbd30bad
    status: OutOfSync
