apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-test
  namespace: argocd
spec:
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 5.1.4
    helm:
      values: |
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws  # Use aws provider with filesystem config
              bucket: backups
              config:
                region: minio
                s3ForcePathStyle: "true"
                s3Url: file:///backups
          volumeSnapshotLocation: []
        
        snapshotsEnabled: false
        
        deployNodeAgent: true
        nodeAgent:
          podVolumePath: /var/lib/kubelet/pods
          privileged: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        # Mount the PVC for backup storage
        extraVolumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: velero-backup-pvc
        
        extraVolumeMounts:
          - name: backup-storage
            mountPath: /backups
        
        schedules:
          test-backup:
            disabled: false
            schedule: "0 3 * * *"
            template:
              ttl: "72h0m0s"
              includedNamespaces:
              - default
              - network
              defaultVolumesToFsBackup: true
        
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        
        credentials:
          useSecret: false
        
        initContainers: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
