apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-storage
  namespace: argocd
spec:
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/brianjlehnen/k8s-homelab.git
    targetRevision: HEAD
    path: cluster/backups/storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
