apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/k8s-homelab.git
    path: apps/adguard-home
    targetRevision: HEAD
    plugin:
      name: sops
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  ignoreDifferences:
  - group: ""
    kind: ConfigMap
    name: adguard-home-config
    jsonPointers:
    - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true