apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: network
  labels:
    app: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      initContainers:
      - name: config-init
        image: busybox
        command: 
        - sh
        - -c
        - |
          cp /config-readonly/AdGuardHome.yaml /config-writable/
          chmod 644 /config-writable/AdGuardHome.yaml
        volumeMounts:
        - name: config
          mountPath: /config-readonly
        - name: work
          mountPath: /config-writable
      containers:
      - name: adguard-home
        image: adguard/adguardhome:latest
        args:
        - --no-check-update
        - --config
        - /opt/adguardhome/work/AdGuardHome.yaml
        - --work-dir
        - /opt/adguardhome/work
        - --no-etc-hosts
        ports:
        - containerPort: 53
          protocol: UDP
          name: dns-udp
        - containerPort: 53
          protocol: TCP
          name: dns-tcp
        - containerPort: 3000
          protocol: TCP
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
        volumeMounts:
        - name: work
          mountPath: /opt/adguardhome/work
      volumes:
      - name: config
        configMap:
          name: adguard-config
      - name: work
        persistentVolumeClaim:
          claimName: adguard-work