apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: network
  labels:
    app: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
        - name: adguard-home
          image: adguard/adguardhome:latest
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /opt/adguardhome/conf/AdGuardHome.yaml
              subPath: AdGuardHome.yaml
            - name: work
              mountPath: /opt/adguardhome/work
      volumes:
        - name: config
          configMap:
            name: adguard-config
        - name: work
          persistentVolumeClaim:
            claimName: adguard-work
