# apps/adguard-home/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: network
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi