apiVersion: v1
kind: Secret
metadata:
    name: adguard-secret
    namespace: network
type: Opaque
stringData:
    admin_password: ENC[AES256_GCM,data:TKAdfFzFvIobnL0M0mKQgF+GP2E=,iv:bDZxWydYfXr1a13UZyQ0M4HLkXBq4kBkYI5sqIlrI+U=,tag:ne8ouU8uqK5lQYRZDZRAbQ==,type:str]
sops:
    age:
        - recipient: age1ek35nyqzsfq5kuz334vntyklkrfq65d8jhuedxrvnc0nf48rzuaqhejwwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bitVNnN4TkNSYkFYb0Fm
            eTFMQXJlYm5QejFvRGVoNElIV1l4V2tFNlJ3CmgxWERoNWlMYm1BWER0ZzJETDNW
            R25OeWZmcEVOM0ZmYmo5Q3EwMGdpZ00KLS0tIGYwL0hLK1p2VHJ4NXE3UVl6Uy91
            eWphVWlDQmFpVDJlbTQyVmFRU1R0d0kKSgL/j/9QakJEZY6eB1qWKVO7sZthLvT0
            FXcR0kxozlIdPFikoMi6reUhc6yBDzXkGdc34RLAvrahlmeBTOnqOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T21:15:54Z"
    mac: ENC[AES256_GCM,data:xZGZIdCVHlpi5GC/6bP58O78eTTxNtZ4dqZlWe1drOUKIZ3swp74ifxP2w70sAawweqdKB+L+HRf4hABTYbyIzekI0tZzWFRcnPIsBW/7Rn6RsqYZ+WPzMJc67KtssA0yeEBpNfZ6hG1+/Y52l67yvpWp2+D6Hqh7RMLbeRx7r0=,iv:y+eoeJ5ptfcwDH2f2SoZrKopxyzMcLC+IXHkDlPVsLg=,tag:kd4CzFgK9VW+kqijhcGxJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
