apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.1
    helm:
      values: |
        global:
          enabled: true
          tlsDisable: false
        
        injector:
          enabled: true
          image:
            repository: "hashicorp/vault-k8s"
            tag: "1.4.1"
          # ADD RESOURCES FOR VAULT AGENT INJECTOR
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
        
        server:
          image:
            repository: "hashicorp/vault"
            tag: "1.15.2"
          
          # ADD RESOURCES FOR VAULT SERVER PODS
          resources:
            requests:
              cpu: "100m"        # Currently using ~50m each
              memory: "100Mi"    # Currently using ~75Mi each
            limits:
              cpu: "200m"        # Allow for crypto operations
              memory: "150Mi"    # Headroom for operations
          
          # High Availability mode
          ha:
            enabled: true
            replicas: 2
            raft:
              enabled: true
              setNodeId: true
              config: |
                ui = true
                listener "tcp" {
                  tls_disable = 0
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  tls_cert_file = "/vault/userconfig/vault-tls/tls.crt"
                  tls_key_file = "/vault/userconfig/vault-tls/tls.key"
                  tls_client_ca_file = "/vault/userconfig/vault-tls/ca.crt"
                }
                
                storage "raft" {
                  path = "/vault/data"
                  retry_join {
                    leader_api_addr = "https://vault-0.vault-internal:8200"
                    leader_ca_cert_file = "/vault/userconfig/vault-tls/ca.crt"
                    leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
                    leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
                  }
                  retry_join {
                    leader_api_addr = "https://vault-1.vault-internal:8200"
                    leader_ca_cert_file = "/vault/userconfig/vault-tls/ca.crt"
                    leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
                    leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
                  }
                }
                
                service_registration "kubernetes" {}
          
          # TLS configuration  
          volumes:
            - name: vault-tls
              secret:
                secretName: vault-tls
          volumeMounts:
            - mountPath: /vault/userconfig/vault-tls
              name: vault-tls
              readOnly: true
          
          # Storage
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: nfs-client
            accessMode: ReadWriteOnce
          
          # Service configuration
          service:
            enabled: true
            type: ClusterIP
            port: 8200
            targetPort: 8200
          
          # Ingress - UPDATED with modern ingressClassName and backend protocol
          ingress:
            enabled: true
            ingressClassName: nginx  # <- Added this line
            annotations:
              # Removed: kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS  # <- Added this line
              cert-manager.io/cluster-issuer: ca-clusterissuer
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              cert-manager.io/private-key-rotation-policy: Always
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            hosts:
              - host: vault.lab1830.com
                paths: ["/"]
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.lab1830.com
        
        ui:
          enabled: true
          serviceType: "ClusterIP"
          serviceNodePort: null
          externalPort: 8200

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle