apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root-certificate
  namespace: cert-manager
spec:
  isCA: true
  commonName: "lab1830.local CA"
  secretName: ca-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
