apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client 
# Change this line:
provisioner: cluster.local/nfs-subdir-external-provisioner # <--- CORRECTED PROVISIONER NAME
parameters:
  archiveOnDelete: "false" 
reclaimPolicy: Delete
# allowVolumeExpansion: true 
# mountOptions:
#   - "vers=3"