apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client 
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false" 
reclaimPolicy: Delete
# allowVolumeExpansion: true # You can add this if you want
# mountOptions:
#   - "vers=3"