# irsigler-helm-repo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: irsigler-helm-repo # Unique name for this secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository # Required label
stringData:
  type: helm
  name: irsigler # Name displayed in ArgoCD UI
  url: https://helm.irsigler.cloud # The new repository URL