apiVersion: v1
kind: Service
metadata:
  name: loki-external
  namespace: logging
  labels:
    app.kubernetes.io/name: loki-external
    app.kubernetes.io/component: logging
    managed-by: argocd
spec:
  type: ClusterIP  # Changed from LoadBalancer
  ports:
  - name: http
    port: 3100
    targetPort: 3100
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: 9095
    protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki