apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:pz/EgZNupjZ/xk7aa+xKgZTjxj6TJnVhbYqX00YmeuFAppuXV8kQQyrPJ9oV7pMIys/dO4gde9AQTqIkA14xHdSN/NGhBsotY86CHH1RVqkpiWlWY4FIyZMEaaDRlTgF9pTReuJPyHm34X3D7dpyY+9yYayxay45ovyHZ6772R601WtrwyR18BMEEx0pza0vDwzbJxBUH36eHrEyGhwvoYOROWr1UFBJ/jTX0ooYmUzfP33XBwxfSVj3rI0T0ZKQU7e5DzBWlzncUA12IC7Bbs7aKakZMy2n5XYyn9LYuHWMQobFj4AK+7k0RUk=,iv:EddKcpZf4BSez+sA8BhOdaLmTlQYEJdGFrBG+pfMEw8=,tag:b+gn/yZvUjdBoNbZ6dxvYA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1ek35nyqzsfq5kuz334vntyklkrfq65d8jhuedxrvnc0nf48rzuaqhejwwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS3BKSkQ4azZJMVB4T2NY
            QkpxSEFNK0RLVWZaeC9seEtyRWxNeldWcjBjCnJUdWxjZXpDYnJmOGN4WFdxL1dz
            eFJUWVdibHZGc0w2TFVDQWEzaTFaWVkKLS0tIFF0WkpsVjh0R3lpNW5aZVZva1pv
            OUFOd2wwcGRHU3V5bXJtTWNQY09Pc2MKzTmuCBoa/EwtpGlDUa05E+vQXbC6h8d8
            cswbOo3IgSjplmRaq7oqb9omj7pqzekgPoiDUvkzlpIJskzR6pjJMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T17:43:22Z"
    mac: ENC[AES256_GCM,data:ZUCgR5vEOBJR2QTURTVCJWpxbkH2yHxSgczEQS8lERmsChWZty1zFE/I6WcHKR9VcFrpsyFn6jAONbnbj7xX2U2L6QM7Zwf3loqR/rQ8g49fi6m8rigKS+dCUQdy2ss1Gyp5OXIsrUDysUPkOSHgaoRA4dAveZw/Z2AEyz99rok=,iv:HY6TETzPL+8ZYculHH4HK1n1fog63VUvC5ocqsV/VE0=,tag:cjdd2C9imvTtexV6gisYig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
