apiVersion: v1
data:
    password: ENC[AES256_GCM,data:C1wyi7rxq1A=,iv:1ynosweZm7h3FAYqiKdV1FHQHZ22ZVwJ7pTHJXBFh6Q=,tag:ZSsTuBiL9/GdNBv1UpbPeQ==,type:str]
    user: ENC[AES256_GCM,data:xempehhrARM=,iv:Acdbu6IM2pZnTWhaClV/iOr4nkaP83bTr/lIXnESqN0=,tag:ethv+ft3o/oC5ahAQTBakQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1ek35nyqzsfq5kuz334vntyklkrfq65d8jhuedxrvnc0nf48rzuaqhejwwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdXV3bTNNRThmejcvbDdV
            S1A0aGJuWUJhc0FkazVTWjQvYjQ2U3cvSUNBCmNQQlo4bE9yUDU5b1dsZGJqWnN3
            Qjd6QlZTWUtyRmkrNk1STDNMejhPT1EKLS0tIEtHb084dTZTb05JWm1sWVVaY05E
            dC9EMklVWWUzN0ZRLzcySnZnQ21kOUUK6eDFxltofhXvXynY9UZr7UeJJitNxvq3
            uChFcET2xPdvuLkx2ANZmg8DscPRI/dYo/4teQOjYxLJSKL5TcGSnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T01:54:19Z"
    mac: ENC[AES256_GCM,data:gUug2aTrLX0LsWyGnzt40BxTR+PVMCcmPABPa3Li+I1Ug+gyfjG3z7CRU7cA/WtjyocdMURqLr6WyhUUhXZF1L7SnEaK/gNazLBWUevJddNiPr6FdzSBfpHU5mi0yLbBaU69SNtm1wpijiPkBUyMawEZ7RDN6scWfPkKMXjlZ9U=,iv:JWCc3iu0L3ROr28K3g5qd9m2R3diLA6E2NwfSKX+31U=,tag:j+XAswLVyQtM+V2M0W/EsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
