apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:C4C4j8q/+b4=,iv:iZCsE39cabFV/5iBYUtE630Ex62bDcspyP2CLKA77dM=,tag:zJ0igN6lki4OwU4aacZwPg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:MG8xnsUphRRIx4oY,iv:gkMqfccmy37PNhNQwpMh2q9NAIE/UTbRrjAa2YnSOrM=,tag:i9UH6aGFWVEZPLKpqF10Ng==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1ek35nyqzsfq5kuz334vntyklkrfq65d8jhuedxrvnc0nf48rzuaqhejwwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbFlEYUhkN2lxNmp3MnVv
            SlZPajJSaldoU1d1OXZ0THNjTEJHUjVycDNRClFaYUFSay9IcGg0eTBBcWFlSUti
            bCt5WS9jVXluc2FOMmtZV1RuTlNSS2cKLS0tIFJqbnRqb3BMM0ZBMXFCSTJ1V05V
            a2ZiYnh6MEZHcVI3ajNNMDRyZDMxWXMKYj0NSKy/9rVRevOHIjl9XvAa72dm7sM6
            gzi0WeLTibpb8NYWKrc3VE7sS6yGXkNwnZ3Mb0B2eQhPuPe2lNfEkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-21T01:18:09Z"
    mac: ENC[AES256_GCM,data:FbH50ySj6Nx9ocgybMPqvp7Ro4IjLsXNWlmyBB6lcG7P8Yx74lEO6FVTaK3wOTeLnlVr2dvLSdAKChfgE8if8JbR2CtV0bJ0Pl+7Kd4PXsTkq5TIagUeEHYLpJhjHo+PCciorEbfe4QdpjjALmmRp1MjEbr7J5mS+2Il2nmTwQI=,iv:EG2fTIr7eKOTctneMGrgRVRC9v5ztif9U+MHgxrjtTA=,tag:pG1vd4IuWV/DVZS9O5BlWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
