# plex-app-definition.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd # ArgoCD Application objects live here
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/plexinc/pms-docker.git # Official Plex Docker & Chart Git repo
    path: charts/plex-media-server                    # Path to the Helm chart within that repo
    targetRevision: master                            # Use the latest chart from the master branch
                                                      # (Consider pinning to a specific Git commit/tag for long-term stability)
    helm:
      valueFiles: # <--- All custom values now come from here
        - https://raw.githubusercontent.com/brianjlehnen/k8s-homelab/main/apps/plex/plex-values-override.yaml # <--- IMPORTANT: Ensure this URL is correct!
  destination:
    server: https://kubernetes.default.svc
    namespace: plex # Deploy Plex into its own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true