apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/k8s-homelab.git
    path: .
    directory:
      recurse: true
      include: "apps/core/adguard-home/app.yaml"  # Only include AdGuard initially
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
