apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin-sops
  namespace: argocd
data:
  sops.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: sops
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml'"
      generate:
        command:
          - sh
          - "-c"
          - |
            for f in $(find . -name '*.yaml'); do
              if grep -q 'sops:' "$f"; then
                echo '---'
                sops --decrypt "$f"
              else
                echo '---'
                cat "$f"
              fi
            done
      lockRepo: false