apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd # This is where ArgoCD Application objects live
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.30.1" # Your specified Loki chart version
    helm:
      values: |
        # 1. Set the deployment mode to SingleBinary
        deploymentMode: SingleBinary

        # 2. Configure and enable the singleBinary deployment target
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: "nfs-client" 
            size: 50Gi

        loki:
          auth_enabled: false

          # --- CRITICAL CHANGE HERE ---
          # Explicitly set the storage type at the Helm values level
          # This informs the chart's helper templates (like loki.commonStorageConfig).
          storage:
            type: filesystem
            # The filesystem sub-section here can use chart defaults for paths (e.g., /var/loki/chunks)
            # as long as they align with commonConfig.path_prefix and your PVC mount.
            # filesystem: # This section might be optional if chart defaults are fine with type: filesystem
            #   chunks_directory: /var/loki/chunks # Often default
            #   rules_directory: /var/loki/rules   # Often default

          # Provide the ENTIRE Loki configuration via loki.structuredConfig
          # This will be rendered as Loki's main config file.
          structuredConfig:
            auth_enabled: false # Consistent with .Values.loki.auth_enabled

            server:
              http_listen_port: 3100
              grpc_listen_port: 9096

            common:
              path_prefix: /var/loki 
              replication_factor: 1
              storage: # This block inside structuredConfig refers to Loki's internal config
                filesystem: # Loki will use these paths within its /var/loki mount
                  chunks_directory: /var/loki/chunks 
                  rules_directory: /var/loki/rules

            distributor:
              ring:
                instance_addr: 127.0.0.1
                kvstore:
                  store: memberlist

            ingester:
              lifecycler:
                address: 127.0.0.1
                ring:
                  kvstore:
                    store: memberlist
                  replication_factor: 1
                final_sleep: 0s
              chunk_idle_period: 1h
              max_chunk_age: 1h
              chunk_target_size: 1572864 
              wal:
                enabled: true
                dir: /var/loki/wal 

            querier:
              engine:
                max_look_back_period: 0s 

            schema_config:
              configs:
                - from: "2024-04-01"
                  store: boltdb-shipper
                  object_store: filesystem 
                  schema: v13 
                  index:
                    prefix: index_ 
                    period: 24h

            storage_config: # This is Loki's internal storage_config
              boltdb_shipper:
                active_index_directory: /var/loki/index 
                cache_location: /var/loki/boltdb-cache 
                shared_store: filesystem 
              filesystem: 
                directory: /var/loki/chunks # This is where boltdb_shipper stores chunks

            limits_config:
              allow_structured_metadata: false
        
        # Ensure other deployment modes/components are off
        write:
          replicas: 0
        read:
          replicas: 0
        backend:
          replicas: 0
        ingester: # Distributed ingester component
          replicas: 0
        distributor: # Distributed distributor component
          replicas: 0
        querier: # Distributed querier component
          replicas: 0
        queryFrontend:
          replicas: 0
        # ... (and other distributed components set to replicas: 0 as before) ...
        compactor:
          replicas: 0

        enterprise:
          enabled: false
        gateway:
          enabled: false 
        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: logging # Install Loki here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true