# Inside your helm.values: | block in loki-app.yaml

# 1. Ensure you're selecting the right deployment mode (e.g., single binary)
# This key and value is an EXAMPLE, find the correct one for your chart version.
# It might be a top-level setting or under 'loki:'.
# Some charts make singleBinary the default if you don't enable other components.
# Let's assume your chart defaults to a mode that might try object storage
# unless explicitly configured otherwise or a simpler mode is chosen.
# If the chart has a simple 'deploymentMode' or 'mode' key:
# deploymentMode: SingleBinary # EXAMPLE - CHECK YOUR CHART

# Or ensure enterprise features are off if that influences storage
# enterprise:
#   enabled: false # This was in the error template, make sure it's false

# This top-level persistence is for the PVC itself
persistence:
  enabled: true
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  size: 50Gi # Or desired size

loki:
  # Ensure this is false if you are not using Loki's built-in auth
  auth_enabled: false

  # This 'config' block is crucial and maps to Loki's own config file.
  # The structure here MUST align with what your Loki chart version expects
  # for configuring filesystem storage for a single binary or simple mode.
  config:
    # Schema config is important for filesystem storage
    schema_config:
      configs:
        - from: "2024-04-01" # Use a recent "from" date for schema
          store: boltdb-shipper # Common for filesystem backend
          object_store: filesystem
          schema: v13 # Or v12/v14 - check compatibility with your Loki & chart version
          index:
            prefix: index_
            period: 24h
    
    # Storage config explicitly for filesystem
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index    # Path *inside* the PVC
        cache_location: /data/loki/boltdb-cache # Path *inside* the PVC
        shared_store: filesystem # Important for boltdb-shipper with filesystem
      filesystem:
        directory: /data/loki/chunks # Path *inside* the PVC where log chunks are stored
    
    # This section defines how long chunks are stored in the ingester's memory before flushing.
    # Not directly related to the error, but good to be aware of.
    # ingester:
    #   chunk_idle_period: 3m
    #   chunk_target_size: 1536000
    #   max_chunk_age: 1h
    #   # ... other ingester settings

    # This limits how far back queries can go, how many streams, etc.
    # Default limits are often fine to start.
    # limits_config:
    #   retention_period: 7d # Example: if you want Loki to enforce retention
    #   # ... other limits

# If your chart has explicit component sections (like write, read, backend)
# ensure they are configured appropriately for single binary or disabled if not used.
# For most 'loki' (non-distributed) charts, you configure 'loki.config' primarily.

# Example: Ensure gateway is disabled if not needed for single binary
# gateway:
#   enabled: false