apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd # This is where ArgoCD Application objects live
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.30.1" # Your specified Loki chart version (ensure this is for the main 'loki' chart)
    helm:
      values: |
        # Paste the entire content of your loki-values.yaml (from above) here,
        # ensuring correct indentation for a YAML multi-line string.
        # Example: the first line 'deploymentMode:' should be indented.

        # 1. Set the deployment mode to SingleBinary
        deploymentMode: SingleBinary

        # 2. Configure and enable the singleBinary deployment target
        singleBinary:
          replicas: 1
          # Persistence configuration for the singleBinary StatefulSet
          persistence:
            enabled: true
            storageClassName: "nfs-client" # Your NFS StorageClass
            size: 50Gi                     # Desired size for Loki data on NFS
            # accessModes defaults to ReadWriteOnce in the chart for singleBinary, which is fine.

        loki:
          # Ensure auth is disabled for simplicity
          auth_enabled: false 

          # Configure Loki's storage backend type to filesystem.
          storage:
            type: filesystem
            # The 'filesystem' sub-section here will use chart defaults for paths like /var/loki/chunks
            # which is fine if singleBinary.persistence mounts the PVC at /var/loki.

          # Provide the schema configuration for filesystem with boltdb-shipper.
          schemaConfig:
            configs:
              - from: "2024-04-01" 
                store: boltdb-shipper
                object_store: filesystem 
                schema: v13 
                index:
                  prefix: index_
                  period: 24h
          
          commonConfig:
            path_prefix: /var/loki 
            replication_factor: 1 

          ingester:
            lifecycler:
              address: 127.0.0.1 
              ring:
                kvstore:
                  store: memberlist
                replication_factor: 1
              final_sleep: 0s
        write:
          replicas: 0
        read:
          replicas: 0
        backend:
          replicas: 0
        
        # Disable enterprise
        enterprise:
          enabled: false

        # Disable chart's gateway and ingress
        gateway:
          enabled: false
        ingress:
          enabled: false

        # Explicitly set replicas for other modes to 0 to ensure they are disabled if
        # deploymentMode: SingleBinary doesn't fully handle turning them off.
        # Check your chart's values.yaml for these top-level keys if this is necessary.
        # It's often handled by just setting deploymentMode.
        # For this chart version (6.30.1), `deploymentMode: SingleBinary` SHOULD suffice to disable
        # 'write', 'read', 'backend', 'distributor', 'ingester' (as separate components), 'querier' etc.
        # So, I'm omitting explicit disables here to keep it cleaner, relying on 'deploymentMode'.

  destination:
    server: https://kubernetes.default.svc
    namespace: logging # Install Loki here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true