apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-external-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brianjlehnen/k8s-homelab
    targetRevision: HEAD
    path: apps/loki-external-service
  destination:
    server: https://kubernetes.cluster.local
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true