apiVersion: v1
kind: Service
metadata:
  # Removed annotations like kubectl.kubernetes.io/last-applied-configuration
  # Removed creationTimestamp, resourceVersion, uid
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: "1.12.2" # Keep this if it reflects the version you intend to run
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  # clusterIP: 10.43.250.90 # These can be kept or removed. Kubernetes will assign if absent on creation.
  # clusterIPs:
  # - 10.43.250.90
  externalTrafficPolicy: Local # CHANGED from Cluster for better source IP preservation
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - appProtocol: http
      name: http
      nodePort: 32329 # This will still be allocated but traffic should go via LoadBalancer IP
      port: 80
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      nodePort: 31985 # This will still be allocated but traffic should go via LoadBalancer IP
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer 
# The entire 'status:' block has been removed
