---
# Default deny for network namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-default-deny
  namespace: network
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
