apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-pvc
  namespace: default # Using default namespace for this test
spec:
  storageClassName: nfs-client # This MUST match the name of your NFS StorageClass
  accessModes:
    - ReadWriteOnce # nfs-subdir-external-provisioner typically creates RWO volumes
  resources:
    requests:
      storage: 1Gi