apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brianjlehnen/k8s-homelab.git
    targetRevision: HEAD
    path: cluster/monitoring/ingress
    directory:
      include: 'grafana-ingress.yaml'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
