# applications/wiz-connector.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiz-kubernetes-connector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://wiz-sec.github.io/charts
    targetRevision: 3.3.14
    chart: wiz-kubernetes-connector

    helm:
      values: |
        global:
          wizApiToken:
            secret:
              create: false
              name: wiz-api-token
            # THESE ARE REQUIRED BY THE CHART'S TEMPLATING, DESPITE DOCS
            # You must keep these here for the Helm templating to succeed.
            clientId: ***REMOVED***
            clientToken: ***REMOVED***
            # clientEndpoint: "https://api.wiz.us" # Uncomment if needed

        wiz-kubernetes-connector:
          enabled: true
          autoCreateConnector:
            clusterFlavor: Kubernetes
            connectorName: cluster-lab1830
          wiz-broker:
            enabled: true

        wiz-sensor:
          enabled: true
          image:
            repository: wizio.azurecr.io/wiz/sensor
            tag: "1.0.6816" # Confirm with Wiz docs / 'helm search repo wiz-sec/wiz-sensor'
            pullPolicy: IfNotPresent
          imagePullSecret:
            create: false
            name: sensor-image-pull
          sensorClusterName: cluster-lab1830

  destination:
    server: https://kubernetes.default.svc
    namespace: wiz

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true