apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.4.200-192.168.4.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
# Optional: if you have multiple IPAddressPools and want this L2Advertisement
# to only apply to specific pools, you can list them here.
# If omitted or empty, it applies to all pools.
  ipAddressPools:
    - first-pool
