apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/part-of: core
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/k8s-homelab.git
    path: apps/core/adguard-home
    directory:
      exclude: "app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:  # Add this section
  - group: ""
    kind: Secret
    name: adguard-home-credentials
    jsonPointers:
    - /sops
    - /metadata/resourceVersion
    - /metadata/uid