apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - vault.lab1830.com
    - vault-0.vault-internal
    - vault-1.vault-internal
    - vault-2.vault-internal
    - vault.vault.svc.cluster.local
  ipAddresses:
    - 127.0.0.1