apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-backup-pvc
  namespace: velero
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: velero-backup-pv
  storageClassName: ""  # This forces it to use the specific PV
