apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-secrets
  namespace: argocd
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/authentik
    repoURL: git@github.com:brianjlehnen/k8s-homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
