apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.lab1830.com
  oidc.config: |
    name: Authentik
    issuer: http://192.168.4.200/application/o/argocd/
    clientId: argocd
    clientSecret: $oidc.authentik.clientSecret
    requestedScopes: ["openid", "profile", "email"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  policy.default: role:readonly
  policy.csv: |
    g, authentik Admins, role:admin
