apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.lab1830.com
  oidc.config: |
    name: Authentik
    issuer: https://auth.lab1830.com/application/o/argocd/
    clientId: xiavBGJX3wlgs0GPareukepXErx7bHut8qML9u4k
    clientSecret: $oidc.authentik.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
    insecureSkipVerify: true
  policy.default: role:readonly
  policy.csv: |
    g, authentik Admins, role:admin
  # Add TLS configuration for the auth domain
  tls.config: |
    auth.lab1830.com:
      insecureSkipVerify: true