apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  repositories: "- url: git@github.com:brianjlehnen/k8s-homelab.git\n  name: k8s-homelab\n
    \ type: git\n  \n"
  server.insecure: "false"
  url: https://argocd.lab1830.com
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
